package com.zl.courseware.system.model.system;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;


/** SysFunction generated by hbm2java */
@Entity
@Table(name = "sys_function")
public class SysFunction implements java.io.Serializable
{
	/**
	 * 
	 */
	private String                flid;
	private SysMenu               sysMenu;
	private String                flfunctionname;
	private String                flurl;
	private String                fleventfunction;
	private String                flicon;
	private Integer               florder;
	private Set<SysFunctionpower> sysFunctionpowers = new HashSet<SysFunctionpower>(0);
	private String                checked;
	
	
	public SysFunction()
	{
	}
	
	public SysFunction(String flid)
	{
		this.flid = flid;
	}
	
	public SysFunction(String flid, SysMenu sysMenu, String flfunctionname, String flurl, String fleventfunction, String flicon, Integer florder, Set<SysFunctionpower> sysFunctionpowers, String checked)
	{
		super();
		this.flid = flid;
		this.sysMenu = sysMenu;
		this.flfunctionname = flfunctionname;
		this.flurl = flurl;
		this.fleventfunction = fleventfunction;
		this.flicon = flicon;
		this.florder = florder;
		this.sysFunctionpowers = sysFunctionpowers;
		this.checked = checked;
	}
	
	@Id
	@Column(name = "flid", unique = true, nullable = false, length = 32)
	public String getFlid()
	{
		return this.flid;
	}
	
	public void setFlid(String flid)
	{
		this.flid = flid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flmenuid")
	public SysMenu getSysMenu()
	{
		return this.sysMenu;
	}
	
	public void setSysMenu(SysMenu sysMenu)
	{
		this.sysMenu = sysMenu;
	}
	
	@Column(name = "flfunctionname")
	public String getFlfunctionname()
	{
		return this.flfunctionname;
	}
	
	public void setFlfunctionname(String flfunctionname)
	{
		this.flfunctionname = flfunctionname;
	}
	
	@Column(name = "flurl")
	public String getFlurl()
	{
		return this.flurl;
	}
	
	public void setFlurl(String flurl)
	{
		this.flurl = flurl;
	}
	
	@Column(name = "fleventfunction")
	public String getFleventfunction()
	{
		return this.fleventfunction;
	}
	
	public void setFleventfunction(String fleventfunction)
	{
		this.fleventfunction = fleventfunction;
	}
	
	@Column(name = "flicon")
	public String getFlicon()
	{
		return this.flicon;
	}
	
	public void setFlicon(String flicon)
	{
		this.flicon = flicon;
	}
	
	@Column(name = "florder")
	public Integer getFlorder()
	{
		return this.florder;
	}
	
	public void setFlorder(Integer florder)
	{
		this.florder = florder;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysFunction")
	public Set<SysFunctionpower> getSysFunctionpowers()
	{
		return this.sysFunctionpowers;
	}
	
	public void setSysFunctionpowers(Set<SysFunctionpower> sysFunctionpowers)
	{
		this.sysFunctionpowers = sysFunctionpowers;
	}
	
	@Transient
	public String getChecked()
	{
		return checked;
	}
	
	public void setChecked(String checked)
	{
		this.checked = checked;
	}
}
