package com.zl.courseware.system.model.system;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/** SysMenupower generated by hbm2java */
@Entity
@Table(name = "sys_menupower")
public class SysMenupower implements java.io.Serializable
{
	/**
	 * 
	 */
	private String  flid;
	private SysMenu sysMenu;
	private SysRole sysRole;
	
	
	public SysMenupower()
	{
	}
	
	public SysMenupower(String flid)
	{
		this.flid = flid;
	}
	
	public SysMenupower(String flid, SysMenu sysMenu, SysRole sysRole)
	{
		this.flid = flid;
		this.sysMenu = sysMenu;
		this.sysRole = sysRole;
	}
	
	@Id
	@Column(name = "flid", unique = true, nullable = false, length = 32)
	public String getFlid()
	{
		return this.flid;
	}
	
	public void setFlid(String flid)
	{
		this.flid = flid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flmenuid")
	public SysMenu getSysMenu()
	{
		return this.sysMenu;
	}
	
	public void setSysMenu(SysMenu sysMenu)
	{
		this.sysMenu = sysMenu;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flroleid")
	public SysRole getSysRole()
	{
		return this.sysRole;
	}
	
	public void setSysRole(SysRole sysRole)
	{
		this.sysRole = sysRole;
	}
}
