package com.zl.courseware.system.model.system;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/** SysRole generated by hbm2java */
@Entity
@Table(name = "sys_role")
public class SysRole implements java.io.Serializable
{
	/**
	 * 
	 */
	private String                flid;
	private String                flname;
	private Integer               fllevel;
	private String                flcomment;
	private String                flcreatename;
	private String                flmark;
	private Integer               floperationrole;
	private Set<SysFunctionpower> sysFunctionpowers = new HashSet<SysFunctionpower>(0);
	private Set<SysMenupower>     sysMenupowers     = new HashSet<SysMenupower>(0);
	private Set<SysUserrole>      sysUserroles      = new HashSet<SysUserrole>(0);
	
	
	public SysRole()
	{
	}
	
	public SysRole(String flid)
	{
		this.flid = flid;
	}
	
	public SysRole(String flid, String flname, Integer fllevel, String flcomment, String flcreatename, String flmark, Set<SysFunctionpower> sysFunctionpowers, Set<SysMenupower> sysMenupowers, Set<SysUserrole> sysUserroles)
	{
		this.flid = flid;
		this.flname = flname;
		this.fllevel = fllevel;
		this.flcomment = flcomment;
		this.flcreatename = flcreatename;
		this.flmark = flmark;
		this.sysFunctionpowers = sysFunctionpowers;
		this.sysMenupowers = sysMenupowers;
		this.sysUserroles = sysUserroles;
	}
	
	@Id
	@Column(name = "flid", unique = true, nullable = false, length = 32)
	public String getFlid()
	{
		return this.flid;
	}
	
	public void setFlid(String flid)
	{
		this.flid = flid;
	}
	
	@Column(name = "flname")
	public String getFlname()
	{
		return this.flname;
	}
	
	public void setFlname(String flname)
	{
		this.flname = flname;
	}
	
	@Column(name = "fllevel")
	public Integer getFllevel()
	{
		return this.fllevel;
	}
	
	public void setFllevel(Integer fllevel)
	{
		this.fllevel = fllevel;
	}
	
	@Column(name = "flcomment")
	public String getFlcomment()
	{
		return this.flcomment;
	}
	
	public void setFlcomment(String flcomment)
	{
		this.flcomment = flcomment;
	}
	
	@Column(name = "flcreatename")
	public String getFlcreatename()
	{
		return this.flcreatename;
	}
	
	public void setFlcreatename(String flcreatename)
	{
		this.flcreatename = flcreatename;
	}
	
	@Column(name = "flmark", length = 32)
	public String getFlmark()
	{
		return this.flmark;
	}
	
	public void setFlmark(String flmark)
	{
		this.flmark = flmark;
	}
	
	@Column(name = "floperationrole")
	public Integer getFloperationrole()
	{
		return floperationrole;
	}

	public void setFloperationrole(Integer floperationrole)
	{
		this.floperationrole = floperationrole;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
	public Set<SysFunctionpower> getSysFunctionpowers()
	{
		return this.sysFunctionpowers;
	}
	
	public void setSysFunctionpowers(Set<SysFunctionpower> sysFunctionpowers)
	{
		this.sysFunctionpowers = sysFunctionpowers;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
	public Set<SysMenupower> getSysMenupowers()
	{
		return this.sysMenupowers;
	}
	
	public void setSysMenupowers(Set<SysMenupower> sysMenupowers)
	{
		this.sysMenupowers = sysMenupowers;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysRole")
	public Set<SysUserrole> getSysUserroles()
	{
		return this.sysUserroles;
	}
	
	public void setSysUserroles(Set<SysUserrole> sysUserroles)
	{
		this.sysUserroles = sysUserroles;
	}
}
