package com.zl.courseware.system.model.system;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


/** SysUser generated by hbm2java */
@Entity
@Table(name = "sys_user")
public class SysUser implements java.io.Serializable
{
	/**
	 * 
	 */
	private String           flid;
	private String           flname;
	private String           flaccount;
	private String           flpassword;
	private String           fltelephone;
	private Integer          flisadmin;
	private Integer          flstate;
	private String           flcreatename;
	private String           florganizationid;
	private String           fldisplay;
	private Date             flcreatetime;
	private String           flpersonid;
	private Integer          flusertype;
	private Set<SysUserrole> sysUserroles = new HashSet<SysUserrole>(0);
	
	private String flclassid;
	private String flclassname;
	

	public SysUser()
	{
	}
	
	public SysUser(String flid, String fldisplay, Date flcreatetime)
	{
		this.flid = flid;
		this.fldisplay = fldisplay;
		this.flcreatetime = flcreatetime;
	}
	@Id
	@Column(name = "flid", unique = true, nullable = false, length = 32)
	public String getFlid()
	{
		return this.flid;
	}
	
	public SysUser(String flid, String flname, String flaccount, String flpassword, String fltelephone, Integer flisadmin, Integer flstate, String flcreatename, String florganizationid, String fldisplay, Date flcreatetime, String flpersonid, Integer flusertype, Set<SysUserrole> sysUserroles)
    {
	    super();
	    this.flid = flid;
	    this.flname = flname;
	    this.flaccount = flaccount;
	    this.flpassword = flpassword;
	    this.fltelephone = fltelephone;
	    this.flisadmin = flisadmin;
	    this.flstate = flstate;
	    this.flcreatename = flcreatename;
	    this.florganizationid = florganizationid;
	    this.fldisplay = fldisplay;
	    this.flcreatetime = flcreatetime;
	    this.flpersonid = flpersonid;
	    this.flusertype = flusertype;
	    this.sysUserroles = sysUserroles;
    }

	public void setFlid(String flid)
	{
		this.flid = flid;
	}
	
	@Column(name = "flname")
	public String getFlname()
	{
		return this.flname;
	}
	
	public void setFlname(String flname)
	{
		this.flname = flname;
	}
	
	@Column(name = "flaccount")
	public String getFlaccount()
	{
		return this.flaccount;
	}
	
	public void setFlaccount(String flaccount)
	{
		this.flaccount = flaccount;
	}
	
	@Column(name = "flpassword")
	public String getFlpassword()
	{
		return this.flpassword;
	}
	
	public void setFlpassword(String flpassword)
	{
		this.flpassword = flpassword;
	}
	
	@Column(name = "fltelephone")
	public String getFltelephone()
	{
		return this.fltelephone;
	}
	
	public void setFltelephone(String fltelephone)
	{
		this.fltelephone = fltelephone;
	}
	
	@Column(name = "flisadmin")
	public Integer getFlisadmin()
	{
		return this.flisadmin;
	}
	
	public void setFlisadmin(Integer flisadmin)
	{
		this.flisadmin = flisadmin;
	}
	
	@Column(name = "flstate")
	public Integer getFlstate()
	{
		return this.flstate;
	}
	
	public void setFlstate(Integer flstate)
	{
		this.flstate = flstate;
	}
	
	@Column(name = "flcreatename")
	public String getFlcreatename()
	{
		return this.flcreatename;
	}
	
	public void setFlcreatename(String flcreatename)
	{
		this.flcreatename = flcreatename;
	}
	
	@Column(name = "florganizationid", length = 32)
	public String getFlorganizationid()
	{
		return this.florganizationid;
	}
	
	public void setFlorganizationid(String florganizationid)
	{
		this.florganizationid = florganizationid;
	}
	
	@Column(name = "fldisplay", nullable = false, length = 1)
	public String getFldisplay()
	{
		return this.fldisplay;
	}
	
	public void setFldisplay(String fldisplay)
	{
		this.fldisplay = fldisplay;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "flcreatetime", nullable = false, length = 19)
	public Date getFlcreatetime()
	{
		return this.flcreatetime;
	}
	
	public void setFlcreatetime(Date flcreatetime)
	{
		this.flcreatetime = flcreatetime;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUser")
	public Set<SysUserrole> getSysUserroles()
	{
		return this.sysUserroles;
	}
	
	public void setSysUserroles(Set<SysUserrole> sysUserroles)
	{
		this.sysUserroles = sysUserroles;
	}
	
	@Column(name = "flpersonid", length = 32)
	public String getFlpersonid()
    {
    	return flpersonid;
    }

	public void setFlpersonid(String flpersonid)
    {
    	this.flpersonid = flpersonid;
    }
	@Column(name = "flusertype", length = 2)
	public Integer getFlusertype()
    {
    	return flusertype;
    }

	public void setFlusertype(Integer flusertype)
    {
    	this.flusertype = flusertype;
    }
	
	
	@Transient
	public String getFlclassid()
	{
		return flclassid;
	}

	public void setFlclassid(String flclassid)
	{
		this.flclassid = flclassid;
	}

	@Transient
	public String getFlclassname()
	{
		return flclassname;
	}

	public void setFlclassname(String flclassname)
	{
		this.flclassname = flclassname;
	}
}
